services:
    app:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
            args:
                uid: $UID
                gid: $GID
        restart: unless-stopped
        volumes:
            - ../:/var/www/

    webserver:
        image: nginx:1.23
        ports:
            - "${APP_PORT}:80"
        restart: unless-stopped
        volumes:
            - ../:/var/www/
            - ./nginx.conf:/etc/nginx/templates/default.conf.template

    database:
        image: postgres:15.2
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        command: -p ${DB_PORT}
        volumes:
            - postgres-data:/var/lib/postgresql/data

    npm:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.node
            args:
                uid: $UID
                gid: $GID
        volumes:
            - ../:/var/www/

volumes:
    postgres-data:
